### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sudo-owen** [0xmons/TODO#2]
- [x] Add claim page
- [x] Add footer links to socials
- [x] more complicated staking tests for add/remove stake to ensure that, even with multiple parties, users can recover their funds
- [X] randomized tests for staking + high load
- [x] Write spawning contract
- [x] Look into using [Echidna](https://github.com/crytic/echidna) (Maybe also Manticore?)
- [x] Tests for spawning contract
- [x] Documentation for smart contracts repo.
- [x] Get blog.xmons.xyz set up w/ Volta.
- [x] Find best way to linearly vest dev share of tokens.
- [x] Ensure dextools score is high.
- [x] Update XMON token logo
- [x] submit token details to etherscan
- [x] make an image for the XMON token
- [x] Update mon struct w/ id and contractOrder and creatorContract. Also update tests, interface, minter, and spawner accordingly. (improves API design for tokenURI.)
- [x] Update prefixURI to be the contractOrder, rather than the unique ID. Also add prefixURI to the default staker contract. 
- [x] Build out a sidebar for the menu
- [x] Add pausable to monStaker
- [x] add natSpec documentation to monStaker, XMON, and monMinter
- [x] circle logo for 0xmons
- [x] Follow up / RHL and Reff for pixels
- [X] Update home page to better explain the idea + images
- [x] For server-side, add model number to each mon
- [x] Update favicon
- [x] Deploy minter, staker, and spawner contracts.
- [x] whitelist staking contract before launch
- [x] Build staking UI for pool
- [x] Follow up with Duncan for gpt-3 text
- [x] Deploy vesting contract, vest XMON tokens. (https://github.com/88mphapp/88mph-contracts/blob/master/contracts/rewards/Vesting.sol)
- [x] Set up Gnosis multisg, move tokens in there.
- [x] Add LP staking pool
- [x] Whitelist LP staking pool before launch
- [x] In-depth analysis of smart contracts (diagram, write-up, permissions, etc.)
- [x] write a blog post that explains dev schedule (maybe merge with above)
- [x] write a blog post that explains the XMON token / 0xmons project
- [x] initial 8 special NFTs (maybe on Rarible) w/ XMON incentives
- [x] submit token details to coingecko
- [x] write an intro post about myself
- [x] Reach out to marketing once we're live 
- [x] Create dual-staking pools
- [x] Cache info from front-end and reduce redundancy
- [x] Make ZUT collab doc, share w/ team
